#!/bin/sh
# Filename:      grml-bootstrap
# Purpose:       wrapper around debootstrap for installing plain Debian via grml
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Fre Nov 03 17:49:46 CET 2006 [mika]
################################################################################
# http://www.debian.org/releases/stable/i386/apcs04.html.en

set -e # exit on any error

. /etc/grml/lsb-functions
. /etc/grml/script-functions

VERSION='0.1'

case $* in
   -h*|--h*)
     einfo "$0 - wrapper around debootstrap for installing plain Debian via grml"
     einfo "Configure via /etc/debootstrap/config and invoke $0 afterwards."
     eend 0
     exit 0
   ;;
   -v|--v*)
     einfo "$0 version $VERSION"
     einfo "Send bug reports to Michael Prokop <mika@grml.org>."
     eend 0
     exit 0
   ;;
esac

check4progs debootstrap || exit 1
check4root || exit 1

if [ -r /etc/debootstrap/config ] ; then
   . /etc/debootstrap/config
else
   echo "/etc/debootstrap/config could not be read, exiting."
   exit 1
fi

if [ -z "$TARGET" ] ; then
   eerror "Please adjust /etc/debootstrap/config before running ${0}" ; eend 1
   exit 1
fi

if [ -n "$MKFS" ] ; then
   einfo "Running $MKFS on $TARGET"
   $MKFS $TARGET
   eend $?
fi

if [ -n "$TUNE2FS" ] ; then
   einfo "Disabling automatic filesystem check on $TARGET via tune2fs"
   $TUNE2FS $TARGET
   eend $?
fi

# now mount the new partition
if grep -q $TARGET /proc/mounts ; then
   eerror "$TARGEt already mounted, exiting."
else
  einfo "Mounting $TARGET to $MNTPOINT"
  mount -o rw,suid,dev $TARGET $MNTPOINT
  eend $?
fi

# get main packages from a debian-mirror
einfo "Running $DEBOOTSTRAP for release $RELEASE using mirror $MIRROR"
$DEBOOTSTRAP $RELEASE $MNTPOINT $MIRROR
eend $?

einfo "Preparing chroot system"
  cp $CONFFILES/chroot-script $MNTPOINT/bin/chroot-script
  chmod 755 $MNTPOINT/bin/chroot-script
  mkdir $MNTPOINT/etc/debootstrap/

  # make sure we have our files for later use via chroot-script
  cp /etc/debootstrap/config $MNTPOINT/etc/debootstrap/
  cp /etc/debootstrap/packages $MNTPOINT/etc/debootstrap/packages

  # copy any existing existing files to chroot
  [ -d /etc/debootstrap/boot  ] && cp -a /etc/debootstrap/boot/*  $MNTPOINT/boot/
  [ -d /etc/debootstrap/etc   ] && cp -a /etc/debootstrap/etc/*   $MNTPOINT/etc/
  [ -d /etc/debootstrap/share ] && cp -a /etc/debootstrap/share/* $MNTPOINT/share/
  [ -d /etc/debootstrap/usr   ] && cp -a /etc/debootstrap/usr/*   $MNTPOINT/usr/
  [ -d /etc/debootstrap/var   ] && cp -a /etc/debootstrap/var/*   $MNTPOINT/var/
eend 0

einfo "Executing chroot-script now"
chroot $MNTPOINT /bin/chroot-script
eend $?

einfo "Unmount $MNTPOINT"
umount $MNTPOINT
eend $?

if [ "$FSCK" = 'yes' ] ; then
   [ -n "$FSCKTOOL" ] || FSCKTOOL="fsck.${MKFS#mkfs.}"
   einfo "Checking filesystem on $TARGET using $FSCKTOOL"
   $FSCKTOOL $TARGET
   eend $?
fi

einfo "Finished execution of $0 - enjoy your Debian system." ; eend 0

## END OF FILE #################################################################
